// plugins/ztools-developer-plugin/react-vite/src/Read/index.tsx
import { useEffect, useState } from 'react'
import './index.css'

interface ReadProps {
  enterAction: any
}

export default function Read({ enterAction }: ReadProps) {
  const [filePath, setFilePath] = useState('')
  const [fileContent, setFileContent] = useState('')
  const [error, setError] = useState('')

  const handleOpenDialog = () => {
    // 通过 QuickDesk 的 api 打开文件选择窗口
    const files = window.ztools.showOpenDialog({
      title: '选择文件',
      properties: ['openFile']
    })
    if (!files) return
    const filePath = files[0]
    setFilePath(filePath)
    try {
      const content = window.services.readFile(filePath)
      setFileContent(content)
    } catch (err: any) {
      setError(err.message)
      setFileContent('')
    }
  }

  useEffect(() => {
    if (enterAction.type === 'files') {
      // 匹配文件进入，直接读取文件
      const filePath = enterAction.payload[0].path
      setFilePath(filePath)
      try {
        const content = window.services.readFile(filePath)
        setFileContent(content)
      } catch (err: any) {
        setError(err.message)
        setFileContent('')
      }
    }
  }, [enterAction])

  return (
    <div className="read">
      <button onClick={handleOpenDialog}>选择文件</button>
      <div className="read-file">{filePath}</div>
      {fileContent && <pre>{fileContent}</pre>}
      {error && <div className="read-error">{error}</div>}
    </div>
  )
}

// plugins/vibe-coding/public/skills/develop-ztools-plugin/assets/templates/vue-vite/src/Read/index.vue
<script setup lang="ts">
import { ref, watch } from 'vue'

const props = defineProps({
  enterAction: {
    type: Object,
    required: true
  }
})

const filePath = ref('')
const fileContent = ref('')
const error = ref('')

const handleOpenDialog = () => {
  // 通过 QuickDesk 的 api 打开文件选择窗口
  const files = window.ztools.showOpenDialog({
    title: '选择文件',
    properties: ['openFile']
  })
  if (!files) return
  const _filePath = files[0]
  filePath.value = _filePath
  try {
    const content = window.services.readFile(_filePath)
    fileContent.value = content
  } catch (err: any) {
    error.value = err.message
    fileContent.value = ''
  }
}

watch(
  () => props.enterAction,
  (enterAction: any) => {
    if (enterAction.type === 'files') {
      // 匹配文件进入，直接读取文件
      const _filePath = enterAction.payload[0].path

      filePath.value = _filePath
      try {
        const content = window.services.readFile(_filePath)
        fileContent.value = content
      } catch (err: any) {
        error.value = err.message
        fileContent.value = ''
      }
    }
  },
  {
    immediate: true
  }
)
</script>

<template>
  <div class="read">
    <button @click="handleOpenDialog">选择文件</button>
    <div class="read-file">{{ filePath }}</div>
    <template v-if="!!fileContent">
      <pre>
        {{ fileContent }}
      </pre>
    </template>
    <template v-if="!!error">
      <div class="read-error">
        {{ error }}
      </div>
    </template>
  </div>
</template>

<style>
.read {
  padding: 20px;
  box-sizing: border-box;
}

.read > pre {
  background-color: #fff;
  width: 100%;
  overflow: hidden;
  padding: 20px;
  box-sizing: border-box;
  border-radius: 7px;
  margin-top: 20px;
  white-space: break-spaces;
}

.read-file {
  width: 100%;
  margin-top: 20px;
  font-weight: bold;
}

.read-error {
  color: red;
}

@media (prefers-color-scheme: dark) {
  .read > pre {
    background-color: #424242;
  }
}
</style>
